### ISSUE TITLE
question on checkStalledJobs

### ISSUE THREAD

**Issue by davisford** [LewisJEllis/bee-queue#29]
Should `checkStalledJobs` be called from a producer or consumer/worker, or does it not matter?

Currently, I am only calling it from a producer node, but I figured I'd ask.

**Comment by LewisJEllis** [comment]
It doesn't matter as far as the library is concerned, as long as some queue somewhere is calling it. In the interests of maximizing the reliability of "some queue somewhere is calling it", I call it from producers because I consider the activities of the consumer to be the source of uncertainty, risk of lockup/failure, etc. If you don't think your consumers have any more risk of failure than your producers (just sharing the same hard-to-avoid risks of network failure, hardware failure, etc), then running it from your consumers would be quite reasonable.

**Comment by mpinger** [comment]
Since the 'stallInterval' queue setting is used by the producer to prevent stalling it makes sense to call checkStalledJobs() on the producer side so the producer and consumer don't have to coordinate the 'stallInterval' setting when creating a queue. This is useful if your producer and consumer don't share code or settings.
